# Generated by Django 6.0.1 on 2026-04-13 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_shipment'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='bookings.booking')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='users.carrier')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('booking', 'carrier')},
            },
        ),
    ]
