services:
  - type: web
    name: cargolink-backend
    env: python
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "gunicorn cargolink_backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "4"
